control_brace_style = "AlwaysNextLine"
error_on_line_overflow = true
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "One"
imports_layout = "HorizontalVertical"
indent_style = "Visual"
match_block_trailing_comma = true
max_width = 80
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
spaces_around_ranges = true
struct_lit_single_line = false
use_field_init_shorthand = true
wrap_comments = true